typography_spectrum: 0.84277
color:
  brandColors:
    - '#352828'
    - '#fefcfc'
    - '#e9e1e2'
    - '#7d6e5d'
    - '#a4876e'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-79650420-1
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: null
name: A quem interessar possa
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: ''
purpose: []
