name: A quem interessar possa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84277
title: A quem interessar possa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#352828'
    - '#fefcfc'
    - '#e9e1e2'
    - '#7d6e5d'
    - '#a4876e'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
